ALL MIGRATIONS AND MODELS
atulgammastack/demorails6 pull request #1
Opened 2022-08-29 10:01 UTC by atulgammastack

2022-08-30 05:20 UTC, kalpana19sharma requested changes

2022-08-30 05:20 UTC, kalpana19sharma commented on Gemfile
> +gem 'byebug'
`byebug` should have been included by default

2022-08-30 05:20 UTC, kalpana19sharma commented on Gemfile
> +gem 'jquery-rails'
Don't use this gem, use jquery package instead

2022-08-30 05:20 UTC, kalpana19sharma commented on app/controllers/application_controller.rb
> +  def require_login
Rename this method to `authenticate_user`

2022-08-30 05:20 UTC, kalpana19sharma commented on app/controllers/comments_controller.rb
> +
Remove this unnecessary empty line at the start of the class. Check in other files as well

2022-08-30 05:20 UTC, kalpana19sharma commented on app/controllers/comments_controller.rb
> +    @comment.user = current_user
Can we do this in single line?

2022-08-30 05:20 UTC, kalpana19sharma commented on app/controllers/comments_controller.rb
> +      flash[:warn] = @comment.errors.full_messages.join('. ').to_s
Don't use flash messages to show errors. Render the errors in views

2022-08-30 05:20 UTC, kalpana19sharma commented on app/controllers/likes_controller.rb
> +    like = Like.find_by(id: params[:id], post_id: params[:post_id])
why do we need id and post_id both?

2022-08-30 05:20 UTC, kalpana19sharma commented on app/controllers/passwords_controller.rb
> +    user.send_password_reset if user
rename this method

2022-08-30 05:20 UTC, kalpana19sharma commented on app/controllers/posts_controller.rb
> +  before_action :require_login, only:[:new,:index,:show]
Use `%i` syntax for array of symbols

2022-08-30 05:20 UTC, kalpana19sharma commented on app/controllers/posts_controller.rb
> +      redirect_to posts_path
Show a flash message

2022-08-30 05:20 UTC, kalpana19sharma commented on app/controllers/posts_controller.rb
> +      redirect_to new_post_path
Use render in case of errors

2022-08-30 05:20 UTC, kalpana19sharma commented on app/controllers/users_controller.rb
> +    end
Move this logic to a filter

2022-08-30 05:20 UTC, kalpana19sharma commented on app/helpers/application_helper.rb
> +    end
Fix indentation and you should make a method in model to find like for a specific post and user. Try to use associations

2022-08-30 05:20 UTC, kalpana19sharma commented on app/helpers/application_helper.rb
> +    when  'alert' then 'alert- info'
why we have 2 conditions for `alert` and use single quote strings

2022-08-30 05:20 UTC, kalpana19sharma commented on app/javascript/packs/application.js
> -
Why did you remove this code?

2022-08-30 05:20 UTC, kalpana19sharma commented on app/models/post.rb
> +  scope :ordered_by_most_recent, -> {order(created_at: :desc)}
Rename it

2022-08-30 05:20 UTC, kalpana19sharma commented on app/models/user.rb
> +  end
Rewrite this method

2022-08-30 05:20 UTC, kalpana19sharma commented on app/views/layouts/application.html.erb
> +      <% end %>
Let's extract this code in a partial

2022-08-30 05:20 UTC, kalpana19sharma commented on app/views/passwords/edit.html.erb
> +              </div>
Fix indentation and remove unnecessary empty lines

2022-08-30 05:20 UTC, kalpana19sharma commented on app/views/passwords/new.html.erb
> +                 <%= form_with url: passwords_path, :method => :post, :html => {:class => "mx-1 mx-md-4"} do |f|%>
Don't use arrow syntax

2022-08-30 05:20 UTC, kalpana19sharma commented on app/views/passwords/new.html.erb
> +                 <%= form_with url: passwords_path, :method => :post, :html => {:class => "mx-1 mx-md-4"} do |f|%>
And fix spaces

2022-08-30 05:20 UTC, kalpana19sharma commented on app/views/posts/_form.html.erb
> +<% end %>
Fix spaces in all view files

2022-08-30 05:20 UTC, kalpana19sharma commented on app/views/users/show.html.erb
> +                                <span class="glyphicon glyphicon-user  text-primary"></span>
Fix indentation

2022-09-01 05:00 UTC, kalpana19sharma requested changes

2022-09-01 05:00 UTC, kalpana19sharma commented on app/assets/stylesheets/application.scss
> +  }
Fix indentation

2022-09-01 05:00 UTC, kalpana19sharma commented on app/controllers/comments_controller.rb
> +    if @comment.save
Don't use create and save both

2022-09-01 05:00 UTC, kalpana19sharma commented on app/controllers/comments_controller.rb
> +      flash[:success] = "your comment was submitted"
```suggestion
      flash[:success] = "Your comment was submitted."
```

2022-09-01 05:00 UTC, kalpana19sharma commented on app/controllers/comments_controller.rb
> +      flash[:success] = "your comment was submitted"
Fix other sentences

2022-09-01 05:00 UTC, kalpana19sharma commented on app/models/post.rb
> +  scope :recent_posts, -> {order(created_at: :desc)}
spaces

2022-09-01 05:00 UTC, kalpana19sharma commented on app/views/layouts/application.html.erb
> +<% end %>
Indentation

2022-09-01 05:00 UTC, kalpana19sharma commented on app/views/layouts/application.html.erb
> +    <%end %>
Spaces

2022-09-01 05:00 UTC, kalpana19sharma commented on app/views/posts/new.html.erb
> +<% end %>
Extract this logic in a shared partial and fix spaces

2022-09-01 05:00 UTC, kalpana19sharma commented on app/views/shared/_error_messages.html.erb
> +<%end%>
Make this generic so that you can use it for multiple forms

2022-09-01 05:00 UTC, kalpana19sharma commented on app/views/shared/_flash_messages.html.erb
> +<% end %>
new line

2022-09-01 05:00 UTC, kalpana19sharma commented on app/views/users/_form.html.erb
> +                  <%end%>
spaces

2022-09-01 05:00 UTC, kalpana19sharma commented on app/views/users/show.html.erb
> +                <%= "#{@user.first_name}" %>
Why are you using string interpolation?

2022-09-01 05:00 UTC, kalpana19sharma commented on config/routes.rb
> +  resources :likes, only: [:create, :destroy]
Indentation and use `%i` syntax

2022-09-01 09:29 UTC, kalpana19sharma requested changes

2022-09-01 09:29 UTC, kalpana19sharma commented on app/helpers/application_helper.rb
> +    like = Like.find_by(post: post, user: current_user)
Use `post_like_by_user` method and rename the method to `like_by_user`

2022-09-01 10:50 UTC, atulgammastack commented
![Dashboard](https://user-images.githubusercontent.com/108937082/187896140-051783f1-51b5-487e-81ed-20eafa36dde3.png)
![login_page](https://user-images.githubusercontent.com/108937082/187896145-9cda7798-5113-4c0b-91fb-017031b5e0c3.png)
![post_show](https://user-images.githubusercontent.com/108937082/187896151-f3f35fea-3675-4c94-ba3e-ea29bfbacfef.png)
![Signup_page](https://user-images.githubusercontent.com/108937082/187896155-47b08159-699d-4751-9ab5-f14681165ace.png)
![user_profile](https://user-images.githubusercontent.com/108937082/187896157-b9d82510-89e7-43c4-8fb6-208003e5ae44.png)
![users_index](https://user-images.githubusercontent.com/108937082/187896162-c3c0ea6a-6c6f-4b25-9609-8aaf45a49b00.png)


I haven't  added style to the user's index,coz these will done with  work of friendship controller on these page.

2022-09-01 10:53 UTC, atulgammastack commented
![reset_password](https://user-images.githubusercontent.com/108937082/187897431-a0efb192-2e49-4439-9ea3-568efdeccab8.png)
![email_sender](https://user-images.githubusercontent.com/108937082/187897482-99e924fa-58b1-43e2-8621-f7554018674a.png)

2022-09-01 11:54 UTC, kalpana19sharma approved these changes

2022-09-01 11:54 UTC, merged